### ISSUE TITLE
subtitles seems to have encoding problems

### ISSUE THREAD

**Issue by rgl** [ThaUnknown/webtorrent-player#18]
The subtitles seems to have encoding problems, here's a screenshot of Sintel with the Pt subtitles:

![image](https://user-images.githubusercontent.com/43356/145541701-c4218ea9-0a40-4253-b6f4-46af4cd278d3.png)

**Comment by ThaUnknown** [comment]
this is because of the default font i use, not having those glyphs, you can always just replace the font and be on your way, the chars decoded are correct tho
