### ISSUE TITLE
how to include the /sw.js and /lib/subtitles-octopus-worker.* 

### ISSUE THREAD

**Issue by mohamed-ya** [ThaUnknown/webtorrent-player#19]

**Comment by ThaUnknown** [comment]
see https://github.com/ThaUnknown/webtorrent-player/blob/main/index.html
the entire rep is the folder structure for the website too

**Comment by ThaUnknown** [comment]
you can always just go on https://thaunknown.github.io/webtorrent-player/ and view the sources tab
