### ISSUE TITLE
Websocket 403

### ISSUE THREAD

**Issue by anonwins** [ThaUnknown/webtorrent-player#20]
I get this error on every torrent I try:

`WebSocket connection to 'wss://peertube.cpy.re/tracker/socket' failed: Error during WebSocket handshake: Unexpected response code: 403
`
The websocket is returning 403. Tested on firefox & chrome, hosted on 2 different domains. Do you know why this happens? Thanks

I'm not sure I installed everything correctly. In my main folder I have `/sw.js`, `/dist/bundle.js`, `/lib/peer.js` & the octopus files. 

Firefox says:
```
GETwss://peertube.cpy.re/tracker/socket [[HTTP/1.1 403 Forbidden 700ms]]()
05:31:54.589 Failed to load ''. A ServiceWorker intercepted the request and encountered an unexpected error. [sw.js:19:8](https://xcxxxcvxvxvxvxck.com/tsf-cinema-beta/sw.js)
```

Also a URL in my own server throws 404:
`HTTP load failed with status 404. Load of media resource https://xaxax.com/subdir/webtorrent/3f4a4bd12234109e93dc5ec384d0e3d511da06e3/video.mp4 failed.` 
The thing is /webtorrent folder doesn't exist in my server. Should it?

**Comment by ThaUnknown** [comment]
this is an error when connecting to a tracker, it's harmless and doesn't cause any issues

**Comment by anonwins** [comment]
Thanks, indeed when I load the default magnets it works. So the problem is that in normal torrents it can't find web-seeders, right?
I've tried dozens of different well-seeded torrents, but it cannot find seeders. Can you confirm if that's the case? Thanks :dancing_men:
